import { createSlice } from "@reduxjs/toolkit"; // Importing createSlice function from Redux Toolkit

// Defining the initial state for the authentication slice which is default:-
//An initialState object is defined has two properties
const initialState = {
    status : false, // Initial authentication status set to false
    userData: null // Initial user data set to null
};

// Creating the authSlice using createSlice function from Redux Toolkit:-
const authSlice = createSlice({
    name: "auth", // Setting the name of the slice to "auth"
    initialState, // Providing the initial state defined above
    //An object containing Reducers function:-
    reducers: {
        // Defining the login reducer function
        login: (state, action) => {
            state.status = true; // Setting the authentication status to true
            state.userData = action.payload.userData; // Updating the user data with the payload from the action
        },
        // Defining the logout reducer function
        logout: (state) => {
            state.status = false; // Setting the authentication status to false
            state.userData = null; // Clearing the user data
        }
    }
});

// Extracting the action creators from the authSlice (object destructuring)
export const { login, logout } = authSlice.actions;

// Exporting the reducer function generated by createSlice
export default authSlice.reducer;
